In [2]:
Pkg.update()

INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove


In [1]:
using PyCall

In [2]:
@pyimport math

In [3]:
math.sin(math.pi/4)-sin(pi/4)

0.0

In [4]:
x=linspace(0,2*pi,1000);y= sin(3*x + 4*cos(2*x));
plt.plot(x,y,color="red",linewidth=2.0,linestyle="--")
plt.show()

LoadError: plt not defined
while loading In[4], in expression starting on line 2

In [5]:
@pyimport numpy.random as nr

In [7]:
a=nr.rand(3,4)

3x4 Array{Float64,2}:
 0.665401   0.73202    0.936739  0.568906
 0.961513   0.0830748  0.747571  0.756435
 0.0206842  0.60583    0.177855  0.23708 

In [8]:
a

3x4 Array{Float64,2}:
 0.665401   0.73202    0.936739  0.568906
 0.961513   0.0830748  0.747571  0.756435
 0.0206842  0.60583    0.177855  0.23708 

In [5]:
@pyimport matplotlib.pyplot as plt
x=linspace(0,2*pi,1000);y= sin(3*x + 4*cos(2*x));
plt.plot(x,y,color="red",linewidth=2.0,linestyle="--")
plt.show()

LoadError: interrupt
while loading In[5], in expression starting on line 4

In [6]:
@pyimport scipy.optimize as so

In [7]:
so.newton(x->cos(x)-x,1)

0.7390851332151607

In [8]:
@pyimport scipy.optimize as so
@pyimport numpy as np
@pyimport matplotlib.pyplot as plt
@pyimport qutip as qt
@pyimport numpy.linalg as la

In [9]:
@pyimport numpy.linalg as la

In [10]:
@pyimport matplotlib.pyplot as plt

In [11]:
@pyimport qutip as qt

In [17]:
qt.qeye(2)

PyObject Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  1.]]

In [26]:
x=pycall(qt.phasegate(pi/2)*qt.phasegate(pi/2)*qt.phasegate(pi/2))

LoadError: `*` has no method matching *(::PyObject, ::PyObject)
while loading In[26], in expression starting on line 1

In [24]:
x.dims

LoadError: type PyObject has no field dims
while loading In[24], in expression starting on line 1

In [12]:
qt.superop_reps[:_pauli_basis]

fn (generic function with 1 method)

In [13]:
superTest=qt.to_super(qt.qeye(2))

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

In [20]:
qt.sigmax()

PyObject Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.  1.]
 [ 1.  0.]]

In [28]:
test=qt.sigmay()

PyObject Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.+0.j  0.-1.j]
 [ 0.+1.j  0.+0.j]]

In [209]:
(pycall(pybuiltin("map"),PyAny,qt.to_super, [qt.qeye(2), qt.sigmax(), qt.sigmay()]))

3-element Array{Any,1}:
 PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
 PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
 PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]
 [ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]]

In [230]:
sum(map(x-> qt.to_super(x)[:full](),[qt.qeye(2), qt.sigmax(), qt.sigmay()]))/3

4x4 Array{Complex{Float64},2}:
 0.333333+0.0im       0.0+0.0im       0.0+0.0im  0.666667+0.0im
      0.0+0.0im  0.333333+0.0im       0.0+0.0im       0.0+0.0im
      0.0+0.0im       0.0+0.0im  0.333333+0.0im       0.0+0.0im
 0.666667+0.0im       0.0+0.0im       0.0+0.0im  0.333333+0.0im

In [46]:
get(test,[0,1])

2x2 Array{Complex{Float64},2}:
 0.0+0.0im  0.0-1.0im
 0.0+1.0im  0.0+0.0im

In [49]:
print(superTest)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

In [50]:
get(superTest,[0,1,2,3])

4x4 Array{Complex{Float64},2}:
 1.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  1.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  1.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  1.0+0.0im

In [54]:
get(superTest,[0:3])

4x4 Array{Complex{Float64},2}:
 1.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  1.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  1.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  1.0+0.0im

In [56]:
superTest[:issuper]

true

In [53]:
0:3

0:3

In [356]:
function to_superpauli(S):
    """
    Converts a superoperator in the column-stacking basis to the Pauli basis. Note that
    the argument is assumed to act on qubits.
    """
    sqobj=qt.to_super(S)
    nq=int(np.log2(sqobj[:shape][1])/2)
    B=pycall(qt.superop_reps["_pauli_basis"],PyAny,nq)
    sq=np.sqrt(2^nq)
    B=pyeval("B/sq",PyAny,B=B,nq=nq,sq=sq)
    B[:dims] = sqobj[:dims]
    sqobj = pycall(B[:dag]()["__mul__"],PyAny,pycall(sqobj["__mul__"],PyAny,B))
    return sqobj
end

to_superpauli (generic function with 1 method)

In [344]:
nq=int(np.log2(sqobj[:shape][1])/2)

2

In [332]:
ts=qt.qeye(4)
sqobj=qt.to_super(ts)


PyObject Quantum object: dims = [[[4], [4]], [[4], [4]]], shape = [16, 16], type = super, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.

In [355]:
to_superpauli(ts)

B dimensions 
Any[2 2
    2 2]

Any[2 2
    2 2]
SQ dimensions 
Any[4 4
    4 4]


PyObject Quantum object: dims = [[[4], [4]], [[4], [4]]], shape = [16, 16], type = super, isherm = True, superrep = None
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  

In [325]:
ts=qt.qeye(4)
sqobj=qt.to_super(ts)
nq=int(np.log2((sqobj[:shape])[1]/2))
B=pycall(qt.superop_reps["_pauli_basis"],PyAny,nq)
sq=np.sqrt(2^nq)
B=pyeval("B/sq",PyAny,B=B,nq=nq,sq=sq)
       

PyObject Quantum object: dims = [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]], shape = [64, 64], type = super, isherm = False
Qobj data =
[[ 0.35355339+0.j          0.00000000+0.j          0.00000000+0.j         ...,
   0.00000000+0.j          0.00000000+0.j          0.35355339+0.j        ]
 [ 0.00000000+0.j          0.35355339+0.j          0.00000000-0.35355339j
  ...,  0.35355339+0.j          0.00000000-0.35355339j  0.00000000+0.j        ]
 [ 0.00000000+0.j          0.00000000+0.j          0.00000000+0.j         ...,
   0.00000000+0.j          0.00000000+0.j          0.00000000+0.j        ]
 ..., 
 [ 0.00000000+0.j          0.00000000+0.j          0.00000000+0.j         ...,
   0.00000000+0.j          0.00000000+0.j          0.00000000+0.j        ]
 [ 0.00000000+0.j          0.35355339+0.j          0.00000000+0.35355339j
  ...,  0.35355339+0.j          0.00000000+0.35355339j  0.00000000+0.j        ]
 [ 0.35355339+0.j          0.00000000+0.j          0.00000000+0.j         ...,
   

In [326]:
B[:dims]

2x2x3 Array{Any,3}:
[:, :, 1] =
 2  2
 2  2

[:, :, 2] =
 2  2
 2  2

[:, :, 3] =
 2  2
 2  2

In [327]:
sqobj=qt.to_super(ts)
sqobj[:dims]
sqobj

PyObject Quantum object: dims = [[[4], [4]], [[4], [4]]], shape = [16, 16], type = super, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.

In [300]:
function unitarity(S)
    toD=S[:dims][1]-1
    sp=to_superpauli(S)[:full]()[2:end,2:end]^2
    norm(sp/toD,2)
end

unitarity (generic function with 1 method)

In [305]:
S=(qt.qeye(4))

PyObject Quantum object: dims = [[4], [4]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

In [306]:
toD=S[:dims][1]-1

3

In [309]:
sp=to_superpauli(S)

LoadError: PyError (:PyObject_Call) <type 'exceptions.ValueError'>
ValueError('dimension mismatch',)
  File "/Library/Python/2.7/site-packages/qutip/qobj.py", line 403, in __mul__
    out.data = self.data * other.data
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/base.py", line 255, in __mul__
    raise ValueError('dimension mismatch')

while loading In[309], in expression starting on line 1

In [296]:
S[:dims][1]

2

In [248]:
sqobj = pycall(B[:dag]()["__mul__"],PyAny,pycall(sqobj["__mul__"],PyAny,B))
    

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = True, superrep = None
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

In [80]:
qt.superop_reps[:_pauli_basis](1)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = False
Qobj data =
[[ 1.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  1.+0.j  0.-1.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+1.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j -1.+0.j]]

In [81]:
[2]*2

1-element Array{Int64,1}:
 4

In [89]:
np.array(2)

0-dimensional Array{Int64,0}:
2

In [94]:
reshape(Array(Int64,4,2),2,2,2)

2x2x2 Array{Int64,3}:
[:, :, 1] =
 140587557787872  140587441405952
 140587441405952  140587441405952

[:, :, 2] =
                   0  0
 4683743616760283136  0

In [95]:
 a = rand(2,1); A = rand(2,3);

In [96]:
a

2x1 Array{Float64,2}:
 0.42535
 0.38997

In [97]:
A


2x3 Array{Float64,2}:
 0.631872  0.373573  0.326729
 0.68276   0.414178  0.674332

In [98]:
repmat(a,1,3)

2x3 Array{Float64,2}:
 0.42535  0.42535  0.42535
 0.38997  0.38997  0.38997

In [99]:
b=rand(1,2)

1x2 Array{Float64,2}:
 0.728517  0.221581

In [100]:
broadcast(+,a,b)

2x2 Array{Float64,2}:
 1.15387  0.646931
 1.11849  0.611551

In [101]:
broadcast(+,b,A)

LoadError: arrays could not be broadcast to a common size
while loading In[101], in expression starting on line 1

In [109]:
require("densePauliFunctions.jl")

In [111]:
generateFullBasePaulis()

8x2 Array{Complex{Int64},2}:
 1+0im   0+0im
 0+0im   1+0im
 0+0im   1+0im
 1+0im   0+0im
 0+0im   0-1im
 0+1im   0+0im
 1+0im   0+0im
 0+0im  -1+0im

In [112]:
getAllPaulis(7)

Get All Paulis 7
Get All Paulis 6
Get All Paulis 5
Get All Paulis 4
Get All Paulis 3
Get All Paulis 2
Get All Paulis 1
Get All Paulis completed for 2
Get All Paulis completed for 3
Get All Paulis completed for 4
Get All Paulis completed for 5
Get All Paulis completed for 6
Get All Paulis completed for 7


(
16384x16384 Array{Complex{Int64},2}:
 1+0im  0+0im  0+0im   1+0im  0+0im  …  0+0im  1+0im  0+0im  0+0im   1+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  

In [114]:
sevenBitP = ans

(
16384x16384 Array{Complex{Int64},2}:
 1+0im  0+0im  0+0im   1+0im  0+0im  …  0+0im  1+0im  0+0im  0+0im   1+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  0+0im   0+0im
 0+0im  0+0im  0+0im   0+0im  0+0im     0+0im  0+0im  0+0im  

In [126]:
size(sevenBitP[1])

(16384,16384)

In [127]:
sevenBitP[1][16384,:]

1x16384 Array{Complex{Int64},2}:
 1+0im  0+0im  0+0im  -1+0im  0+0im  …  0+0im  1+0im  0+0im  0+0im  -1+0im

In [128]:
pz

LoadError: pz not defined
while loading In[128], in expression starting on line 1

In [130]:
z

LoadError: z not defined
while loading In[130], in expression starting on line 1

In [131]:
pz=[1 0;0 -1]

2x2 Array{Int64,2}:
 1   0
 0  -1

In [132]:
kron(pz,kron(pz,pz))

8x8 Array{Int64,2}:
 1   0   0  0   0  0  0   0
 0  -1   0  0   0  0  0   0
 0   0  -1  0   0  0  0   0
 0   0   0  1   0  0  0   0
 0   0   0  0  -1  0  0   0
 0   0   0  0   0  1  0   0
 0   0   0  0   0  0  1   0
 0   0   0  0   0  0  0  -1

In [143]:
pycall(qt.superop_reps["_pauli_basis"],PyAny,1)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = False
Qobj data =
[[ 1.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  1.+0.j  0.-1.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+1.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j -1.+0.j]]

In [144]:
qt.superop_reps[:_pauli_basis](1)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = False
Qobj data =
[[ 1.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  1.+0.j  0.-1.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+1.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j -1.+0.j]]

In [145]:
qt.sigmax()

PyObject Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.  1.]
 [ 1.  0.]]

In [151]:
SX=qt.to_super(qt.sigmax())

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]

In [148]:
B=pycall(qt.superop_reps["_pauli_basis"],PyObject,1)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = False
Qobj data =
[[ 1.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  1.+0.j  0.-1.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+1.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j -1.+0.j]]

In [169]:
get(pyeval("A*B*C",PyAny,A=B[:dag](),B=(SX),C=B),[0,1,2,3])/2

4x4 Array{Complex{Float64},2}:
 1.0+0.0im  0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  1.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  -1.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im   0.0+0.0im  -1.0+0.0im

In [173]:
pycall(operator.mul,PyAny,qt.to_super(qt.sigmax()),qt.to_super(qt.sigmax()))

LoadError: operator not defined
while loading In[173], in expression starting on line 1

In [176]:
pybuiltin("operator.mul")

LoadError: key not found: "operator.mul"
while loading In[176], in expression starting on line 1

In [177]:
B

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = [4, 4], type = super, isherm = False
Qobj data =
[[ 1.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  1.+0.j  0.-1.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+1.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j -1.+0.j]]

In [188]:
pycall((B[:dag]()[:__mul__](qt.to_super(qt.sigmax()))["__mul__"]),PyArray,B)

LoadError: key not found: "__array_interface__"
while loading In[188], in expression starting on line 1

In [229]:
pycall(B["__mul__"],PyAny,(qt.to_super(qt.sigmax())))[:full]()

4x4 Array{Complex{Float64},2}:
  1.0+0.0im  0.0+0.0im  0.0+0.0im  1.0+0.0im
  0.0+0.0im  0.0-1.0im  1.0+0.0im  0.0+0.0im
  0.0+0.0im  0.0+1.0im  1.0+0.0im  0.0+0.0im
 -1.0+0.0im  0.0+0.0im  0.0+0.0im  1.0+0.0im

In [219]:
map((x,y)->x^2+3*y,[2,2,2],[3,4])

LoadError: dimensions must match
while loading In[219], in expression starting on line 1

In [357]:
make_count = function()
    count = 0
    function()
        so_far=count
        count +=1
        so_far
    end
end


(anonymous function)

In [359]:
a=make_count()

(anonymous function)

In [367]:
a()

5

In [365]:
b=make_count()

(anonymous function)

In [368]:
b()

1