# Quick overview of how to generate the 'stabilisers' for the Cleve paper

## This is used to actually generate the relevant Clifford gates in a different (Julia) workbook called "The Cleve Paper"

Obviously the next line will depend on where you are, but change into the finite-fields directory.

This workbook assumes Python3 (but should work with python2.7 with minimal changes --- not tested)

Note that PyCall in Julia is set up to use Python 2.7 by default. This should be changed, which is slightly involved but not difficult.

NOTE: if when you run the notebook you see, for example, in output 4 \\u2208 rather than $\in$, then it may be you are running this in IJulia jupyter rather than a 'jupyter notebook' started from the command line. At least that's what happens to me.

In [1]:
cd '../finite-fields/'

/Users/robin/Dropbox (Sydney Uni)/Juqst/finite-fields


In [2]:
# All the relevant functions are in SLFunctions, but I will (later) step through what is going on

import numpy as np
from finitefield import *
from SLFunctions import *


In [3]:
# We can generate the FiniteField objects as follows
# NOTE there is a random element to this as we randomly find an irreducible polynomial over Z/p

# So here we are generating a binary field i.e. modulus 2 (0 or 1), of third degree polynomials (upto x^3)
# The print out is the basis chosen - this might change each time the kernel is restarted
F23=FiniteField(2,3)




1 + 0 x^1 + 0 x^2 + 1 x^3
1 + 1 x^1 + 1 x^2 + 1 x^3
1 + 1 x^1 + 0 x^2 + 1 x^3


So we have a created a finite field with modulus 2 and of degree 3, this is modeled as a binary coefficient polynomial e.g $a_0 + a_1x + a_2x^2$, where $a_i$ is ${0,1}$

The beauty of the finite-field package is that it allows us to easily add/multiply/divide and take inverses of these fields. We will use this extensively later on. 

The output from the instantiation above is it attempting to find the polynomial that will generate the field. This is used to get the dual basis. Note it is not unique and might change every time the kernel restarts. The dual basis will change depending on this polynomial (so needs to be recalculated) - more later.

In [4]:
# This is just a helper to get the basis elements of the field
# If we were to express them as vectors they would be: (0,0,1), (0,1,0) and (1,0,0)
basis3=getPolyBasis(F23)
basis3

[1 ∈ F_{2^3}, 0 + 1 x^1 ∈ F_{2^3}, 0 + 0 x^1 + 1 x^2 ∈ F_{2^3}]

In [5]:
# This allows us to extract the matrices that translate between the above basis and its dual
w,wb=getW_WBForPoly(F23)

In [6]:
w

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [7]:
wb

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [8]:
# A quick sanity check - translate into the dual and back again.
for i in basis3:
    print(i," => ",toPoly(F23,translateWithW(w,i))," ==> ", toPoly(F23,translateWithW(wb,toPoly(F23,translateWithW(w,i)))))


1 ∈ F_{2^3}  =>  1 ∈ F_{2^3}  ==>  1 ∈ F_{2^3}
0 + 1 x^1 ∈ F_{2^3}  =>  0 + 0 x^1 + 1 x^2 ∈ F_{2^3}  ==>  0 + 1 x^1 ∈ F_{2^3}
0 + 0 x^1 + 1 x^2 ∈ F_{2^3}  =>  0 + 1 x^1 ∈ F_{2^3}  ==>  0 + 0 x^1 + 1 x^2 ∈ F_{2^3}


# The code in SLFuntions just allows you to directly get the stabilisers for a certain 'n' = qubits
# The julia worksheet 'The Cleve Paper' shows how to use these to generate actual clifford gates

# Below I discuss how this works, for those interested.

In [9]:
getF2Stabilisers()

0 + 0 x^1 + 1 x^2
0 + 0 x^1 + 1 x^2
0 + 1 x^1 + 1 x^2
1 + 1 x^1 + 1 x^2


[[[0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0]],
 [[0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 1], [0, 1, 1, 1]],
 [[0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]],
 [[0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 1, 1], [0, 1, 1, 0]],
 [[0, 0, 0, 1], [0, 0, 1, 1], [1, 1, 0, 0], [1, 0, 0, 0]],
 [[0, 0, 0, 1], [0, 0, 1, 1], [1, 1, 0, 1], [1, 0, 1, 1]],
 [[0, 0, 0, 1], [0, 0, 1, 1], [1, 1, 1, 0], [1, 0, 0, 1]],
 [[0, 0, 0, 1], [0, 0, 1, 1], [1, 1, 1, 1], [1, 0, 1, 0]],
 [[0, 0, 1, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 1, 0, 0]],
 [[0, 0, 1, 1], [0, 0, 1, 0], [0, 1, 0, 1], [1, 1, 1, 1]],
 [[0, 0, 1, 1], [0, 0, 1, 0], [0, 1, 1, 0], [1, 1, 0, 1]],
 [[0, 0, 1, 1], [0, 0, 1, 0], [0, 1, 1, 1], [1, 1, 1, 0]],
 [[0, 1, 0, 0], [1, 1, 0, 0], [0, 0, 1, 1], [0, 0, 1, 0]],
 [[0, 1, 1, 1], [1, 1, 1, 0], [0, 0, 1, 1], [0, 0, 1, 0]],
 [[0, 1, 0, 1], [1, 1, 1, 1], [0, 0, 1, 1], [0, 0, 1, 0]],
 [[0, 1, 1, 0], [1, 1, 0, 1], [0, 0, 1, 1], [0, 0, 1, 0]],
 [[0, 1, 0, 0], [1, 1, 0, 0], [1, 0, 1, 1], [0, 1, 1, 0]

# So in order to find the stabiliser What we need to do is 

- get w and wb (so we can translate to and from the dual basis)
- get the SL matrices for this field
- translate using wb to w
- multiply by SL
- translate back to wb

## This example will be for 2-qubits
### Check the basis states are working, convert to one then convert back

In [10]:
F22 = FiniteField(2,2)
basis2=getPolyBasis(F22)
w2,w2b=getW_WBForPoly(F22)
for i in basis2:
    start= toPoly(F22,translateWithW(w2b,i))
    # Here is where to do the GL thing.
    s2=toPoly(F22,translateWithW(w2,start))
    print(i,"--->",start,"---->",s2)
    


1 ∈ F_{2^2} ---> 1 + 1 x^1 ∈ F_{2^2} ----> 1 ∈ F_{2^2}
0 + 1 x^1 ∈ F_{2^2} ---> 1 ∈ F_{2^2} ----> 0 + 1 x^1 ∈ F_{2^2}


### I have automated the finding of the SL Groups, here we do it for F22

Essentially a way we can do this (which works not too slowly up to about F26) is just to brute force it.

Members of $SL_2(GF(2^n))$ can be written as a matrix:

$\left(\begin{array}{cc}\alpha&\beta\\\gamma&\delta\end{array}\right)$, where each of $\alpha,\beta,\delta,\gamma$ are (effectively) bit strings, $n$-bits long. ie. are members of our Field (here F22). Then we required: $\alpha\delta+\beta\gamma=1$ (note the sign here is +, but we are dealing with modulo 2, so minus is the same thing).

So the brute force method is just to loop over every possible $\alpha,\beta,\delta$ and $\gamma$, check the condition, keep it if satisfied and throw it away if not.

In [11]:
field,slm = setUpSLGroups(F22)
# This gives up back the field i.e. all the different values each of α,β,γ and δ can take.
# Then SLM is an array, where each element is the 'indexed' value of these variables. ie. 3 = 3rd element of the field

In [12]:
field

[0 ∈ F_{2^2}, 0 + 1 x^1 ∈ F_{2^2}, 1 ∈ F_{2^2}, 1 + 1 x^1 ∈ F_{2^2}]

In [13]:
slm # obviously its a bit long to print for > F22

[[0, 1, 3, 0],
 [0, 1, 3, 1],
 [0, 1, 3, 2],
 [0, 1, 3, 3],
 [0, 2, 2, 0],
 [0, 2, 2, 1],
 [0, 2, 2, 2],
 [0, 2, 2, 3],
 [0, 3, 1, 0],
 [0, 3, 1, 1],
 [0, 3, 1, 2],
 [0, 3, 1, 3],
 [1, 0, 0, 3],
 [1, 0, 1, 3],
 [1, 0, 2, 3],
 [1, 0, 3, 3],
 [1, 1, 0, 3],
 [1, 1, 1, 2],
 [1, 1, 2, 1],
 [1, 1, 3, 0],
 [1, 2, 0, 3],
 [1, 2, 1, 1],
 [1, 2, 2, 0],
 [1, 2, 3, 2],
 [1, 3, 0, 3],
 [1, 3, 1, 0],
 [1, 3, 2, 2],
 [1, 3, 3, 1],
 [2, 0, 0, 2],
 [2, 0, 1, 2],
 [2, 0, 2, 2],
 [2, 0, 3, 2],
 [2, 1, 0, 2],
 [2, 1, 1, 1],
 [2, 1, 2, 3],
 [2, 1, 3, 0],
 [2, 2, 0, 2],
 [2, 2, 1, 3],
 [2, 2, 2, 0],
 [2, 2, 3, 1],
 [2, 3, 0, 2],
 [2, 3, 1, 0],
 [2, 3, 2, 1],
 [2, 3, 3, 3],
 [3, 0, 0, 1],
 [3, 0, 1, 1],
 [3, 0, 2, 1],
 [3, 0, 3, 1],
 [3, 1, 0, 1],
 [3, 1, 1, 3],
 [3, 1, 2, 2],
 [3, 1, 3, 0],
 [3, 2, 0, 1],
 [3, 2, 1, 2],
 [3, 2, 2, 0],
 [3, 2, 3, 3],
 [3, 3, 0, 1],
 [3, 3, 1, 0],
 [3, 3, 2, 3],
 [3, 3, 3, 2]]

In [14]:
# which is what we were expecting
len(slm)

60

In [15]:
def getAlpha(field,no):
    """ Returns the actualy block [alpha,beta//gamma,delta]
        nicely wrapped up in a numpy array. Which allows us
        to nicely np.dot() [array multiply] it later
        Because of the way types work it all just happens in the correct
        field.
    """
    return np.array([ [field[no[0]],field[no[1]] ], [ field[no[2]],field[no[3]]]])

In [16]:
mat=getAlpha(field,slm[0])


In [17]:
mat

array([[0 ∈ F_{2^2}, 0 + 1 x^1 ∈ F_{2^2}],
       [1 + 1 x^1 ∈ F_{2^2}, 0 ∈ F_{2^2}]], dtype=object)

# So now we are looking at equations around (13) in the paper.

## Our gate is defined by what it does to both the X paulis and the Z paulis

In GL2 if we start with the following (the |00> state), which has anti-stabilizers $XI$ and $IX$ and stabilizers $ZI$ and $IZ$, then we can represent that in Aaronson form (see A Stabilizer run through) as: 

$\left(\begin{array}{ccccc}X&I&&I&I\\I&X&&I&I\\=&=&=&=&=\\I&I&&Z&I\\I&I&&I&Z\end{array}\right)$,

where I have written $X$ or $Z$ to make it clear what that translates to, but in reality its just a 1.

## So I need to set up the vectors for that state (ie. each of the rows above). Then we will multiply by each the appropriate M (which comes from getAlpha(field,1..slm))

- its going to be xi ii/ix ii/ii zi/ii iz for GL2^2
- So iterate through field size, setting everything to zero (translated zero)
- Apart from the one we are at which we set to that polybasis for x
- and the translated polybase for z (<--- this is important in the paper superscripted b is in the dual basis - see first few lines of section 4).

In [18]:
def createStabiliserBasis(x):
    """ Returns the matrices for the field x
    That are required to form the stabiliser states
    You would normally multiply this by the relevant SL matrix
    to get the stabiliser state that represents the clifford you want    
    """ 
    matrices=[]
    w,wb=getW_WBForPoly(x)
    # This first bit is effectively just returning the XI, IX bits
    # e.g. for 2 qubits matrices will end up looking like: [[1, 0], [0, 1]]
    for i in range(0,x.degree):
        makingIt=[]
        for pre in range(0,i):
            makingIt = makingIt+[0]
        makingIt=makingIt+[1]
        if (i+1<= x.degree):
            for aft in range(i+1,x.degree):
                makingIt=makingIt+[0]
        matrices = matrices + [makingIt]
    samples=[]
    # Then for the X part its the matrix and 0000, in the correct field
    for i in matrices:
        samples = samples + [np.array([[x(i)],[x([0])]])]
    # For the Z part its 0000 and the matrix, but remembering to translate into the dual basis.
    for i in matrices:
        samples = samples + [np.array([[x(0)],[toPoly(x,translateWithW(wb,x(i)))]])]
    return samples

In [19]:
stabsA = createStabiliserBasis(F22)
stabsA

[array([[1 ∈ F_{2^2}],
        [0 ∈ F_{2^2}]], dtype=object), array([[0 + 1 x^1 ∈ F_{2^2}],
        [0 ∈ F_{2^2}]], dtype=object), array([[0 ∈ F_{2^2}],
        [1 + 1 x^1 ∈ F_{2^2}]], dtype=object), array([[0 ∈ F_{2^2}],
        [1 ∈ F_{2^2}]], dtype=object)]

### What are we expecting to see with 2 qubits
- The first one will be the 'polynomial' translation of [1,0][0,0]
- The second one will be the 'polynomial' translation of [0,1][0,0]
- The third one will be the 'polynomial' translation of [0,0]DUALBASIS([1,0])
- The fourth one will be the 'polynomial' translation of [0,0]DUALBASIS([0,1])


In [20]:
for i in stabsA:
    print(i,"\n======\n")

[[1 ∈ F_{2^2}]
 [0 ∈ F_{2^2}]] 

[[0 + 1 x^1 ∈ F_{2^2}]
 [0 ∈ F_{2^2}]] 

[[0 ∈ F_{2^2}]
 [1 + 1 x^1 ∈ F_{2^2}]] 

[[0 ∈ F_{2^2}]
 [1 ∈ F_{2^2}]] 



So we take each of the "getAlpha" SL members and multiply each stabsA by it and this will give us our $a'$ and $b'$ of equation (12), which are the stabilised states of the Clifford we want.


In [21]:
mat=getAlpha(field,slm[1])

In [22]:
def stabiliserFori(field,slm,no,stabsA):
    fullStabiliserX = []
    fullStabiliserZ = []
    mat=getAlpha(field,slm[no])
    for i in stabsA:
          temp =  np.dot(mat,i)
          # remember to translate
          fullStabiliserX.append(polyToList(temp[0,0]))
          fullStabiliserZ.append(polyToList(toPoly(F22,translateWithW(w2b,temp[1,0]))))
    return fullStabiliserX,fullStabiliserZ


In [23]:
for i,idx in enumerate(slm):
    print(stabiliserFori(field,slm,i,stabsA))


([[0, 0], [0, 0], [1, 0], [0, 1]], [[0, 1], [1, 1], [0, 0], [0, 0]])
([[0, 0], [0, 0], [1, 0], [0, 1]], [[0, 1], [1, 1], [1, 1], [1, 0]])
([[0, 0], [0, 0], [1, 0], [0, 1]], [[0, 1], [1, 1], [0, 1], [1, 1]])
([[0, 0], [0, 0], [1, 0], [0, 1]], [[0, 1], [1, 1], [1, 0], [0, 1]])
([[0, 0], [0, 0], [1, 1], [1, 0]], [[1, 1], [1, 0], [0, 0], [0, 0]])
([[0, 0], [0, 0], [1, 1], [1, 0]], [[1, 1], [1, 0], [1, 1], [1, 0]])
([[0, 0], [0, 0], [1, 1], [1, 0]], [[1, 1], [1, 0], [0, 1], [1, 1]])
([[0, 0], [0, 0], [1, 1], [1, 0]], [[1, 1], [1, 0], [1, 0], [0, 1]])
([[0, 0], [0, 0], [0, 1], [1, 1]], [[1, 0], [0, 1], [0, 0], [0, 0]])
([[0, 0], [0, 0], [0, 1], [1, 1]], [[1, 0], [0, 1], [1, 1], [1, 0]])
([[0, 0], [0, 0], [0, 1], [1, 1]], [[1, 0], [0, 1], [0, 1], [1, 1]])
([[0, 0], [0, 0], [0, 1], [1, 1]], [[1, 0], [0, 1], [1, 0], [0, 1]])
([[0, 1], [1, 1], [0, 0], [0, 0]], [[0, 0], [0, 0], [1, 0], [0, 1]])
([[0, 1], [1, 1], [0, 0], [0, 0]], [[1, 0], [0, 1], [1, 0], [0, 1]])
([[0, 1], [1, 1], [0, 0], [0, 0]],