## The purpose of this sheet is just to show some of the ways Julia can interact with python

It recaps how to get Julia talking to python, then goes through some of the syntax.

Some of the syntax takes a bit of getting used to, for instance if you want to use qutip.

There is no real rhyme or reason for the examples shown below, they are just illustrative of the syntax needed.

All these workbooks are designed to use Python 3, but if you have the "Julia conda environment" from miniconda then it defaults to Python 2 --- this is just a document of how I got it to move to three (I have eventually decided its time to move on).

If you have already installed PyCall and Conda, then check your version
`
@pyimport sys
print(sys.version)
`

If its 2.7 something then you might want to consider.

(Possibly best to do this in the terminal REPL)

## Remove PyCall and Conda
`
Pkg.rm("PyCall")
Pkg.rm("Conda")
`

## Set your environment variables:


### if you want to use the miniconda environment rather than one on your machine
`ENV["PYTHON"] = "" `
### if you want python3
`ENV["CONDA_JL_VERSION"]="3"`

## Remove existing deps - I did this in the shell but the following 'should' work
`
rm(Pkg.dir("PyCall","deps","PYTHON"))
rm(Pkg.dir("Conda","deps",recursive=True))
`
## Reinstall
`
Pkg.add("Conda")
Pkg.add("PyCall")
`
## Build
`
Pkg.build("Conda")
Pkg.build("PyCall")
`
## Update
`
Pkg.update()
`
## Then see if IJulia still works!
`
using IJulia
`

In [1]:
# Assuming we are in a directory one off the root.
include("../juliaCode/open-systems.jl")
include("../juliaCode/PTSM.jl")
include("../juliaCode/Initial.jl")
include("../juliaCode/Symplectic.jl")
include("../juliaCode/loadHelpers.jl")

Created:
-  superCliffords
-  operatorCliffords
-  superPaulis
-  operator Paulis
-  pI,pX,pY,pZ
- T gate as piBy8 and superPiBy8

- **makeSuper(operator)**

- **findClifford(x)** (super and operator

- **checkFrame(x)** - operator

- **findInThis(needle,haystack)**

- minGens, min4Gens, allGens *twoGenSet, fourGen

- **genA2RotateOperatorClifford(x)**

- **genAFaulty2RotateClifford(x,noiseRotation-matrix)**

- **genAFaulty2RotateOperatorClifford(x,noiseRotation-matrix)**

- **genAFaulty4RotateClifford(x,noiseRotation-matrix)**

- **genAFaulty4RotateOperatorClifford(x,noiseRotation-matrix)**

- **genAFaultyClifford(x,noiseRotation-matrix)**

- **getFidelity(gate,clifford)**
-  **twirl(sequence,victim)**
-  **extractFidelity(sc)**

- **makeRuns(getNumbers,number,gateGenerator,noise,initialState,endState)**

- **doRuns(theGeneratorFunction,)**

doRuns

In [2]:
# Julia can use your existing Python installation or can have its 'own' installation.
#Here I am assuming you are using Julia's Conda - just to make sure everything we need is installed.

#Recall: e.g. Pkg.add("Conda") <- if you haven't already added the packages.

using Conda
using PyCall

### You may need to add the channels

>  Conda.add_channel("conda-forge")

>  Conda.add_channel("cvxgrp")


In [4]:
# if you gate an update conda warning, the following will work
Conda.runconda(`update -y conda`)

Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/robin/.julia/v0.6/Conda/deps/usr:
#
conda                     4.3.33                   py27_0    conda-forge


In [4]:
# Check if you need to add the following (this takes a bit of time)

print("==== SCIPY\n")
Conda.add("scipy")
print("==== QUTIP\n")
Conda.add("qutip")
print("==== LIBGCC\n")
Conda.add("libgcc")
print("==== CVXPY\n")
Conda.add("cvxpy")

==== SCIPY
Solving environment: ...working... done


certifi 2017.11.5: ########## | 100% 
numpy 1.14.0: ########## | 100% 
openblas 0.2.20: ########## | 100% 
ca-certificates 2017.11.5: ########## | 100% 
conda 4.3.33: ########## | 100% 
openssl 1.0.2n: ########## | 100% 
scipy 1.0.0: ########## | 100% 
blas 1.1:            |   0% 


## Package Plan ##

  environment location: /Users/robin/.julia/v0.6/Conda/deps/usr

  added / updated specs: 
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2017.11.5          |           py36_0         195 KB  conda-forge
    numpy-1.14.0               |py36_blas_openblas_200         3.9 MB  conda-forge
    openblas-0.2.20            |                7        20.1 MB  conda-forge
    ca-certificates-2017.11.5  |                0         145 KB  conda-forge
    conda-4.3.33               |           py36_0         515 KB  conda-forge
    openssl-1.0.2n             |                0         3.3 MB  conda-forge
    scipy-1.0.0                |py36_blas_openblas_201        15.7 MB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    ------------------------------------------------------------
                               

blas 1.1: ########## | 100% 

done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==== QUTIP
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/robin/.julia/v0.6/Conda/deps/usr:

The following NEW packages will be INSTALLED:

    cython:    0.27.3-py36_0                 conda-forge
    qutip:     4.2.0-np113py36_2             conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env: 2.6.0-h36134e3_0                          --> 2.6.0-0                       conda-forge

The following packages will be DOWNGRADED:

    numpy:     1.14.0-py36_blas_openblas_200 conda-forge [blas_openblas] --> 1.13.3-py36_blas_openblas_201 conda-forge [blas_openblas]

conda-env-2.6. 100% |###############################| Time: 0:00:00   1.60 MB/s
cython-0.27.3- 100% |###############################| Time: 0:00:02   1.20 MB/s
numpy-1.13.3-p 100% |###############################| Time: 0:00:01   3.77 MB/s
qutip-4.2.0-np 100% |###############################| Time: 0:00:0

In [5]:
# Some trivial examples as per the docs.
@pyimport math

In [6]:
math.sin(math.pi/4)-sin(pi/4)

0.0

In [7]:
@pyimport numpy.random as nr

In [8]:
a=nr.rand(3,4)

3×4 Array{Float64,2}:
 0.871419   0.116292  0.584786  0.44581   
 0.76435    0.743394  0.552925  0.0258917 
 0.0941852  0.249873  0.131864  0.00506953

In [9]:
a

3×4 Array{Float64,2}:
 0.871419   0.116292  0.584786  0.44581   
 0.76435    0.743394  0.552925  0.0258917 
 0.0941852  0.249873  0.131864  0.00506953

In [10]:
# WARNING OPENS UP WINDOW - you will need to close it to move on.

@pyimport matplotlib.pyplot as plt
x=linspace(0,2*pi,1000);
y= sin.(3*x + 4*cos.(2*x));
plt.plot(x,y,color="red",linewidth=2.0,linestyle="--")
plt.show()

In [11]:
@pyimport scipy.optimize as so

In [12]:
so.newton(x->cos(x)-x,1)

0.7390851332151607

In [13]:
#@pyimport scipy.optimize as so
@pyimport numpy as np
@pyimport matplotlib.pyplot as plt
@pyimport qutip as qt
@pyimport numpy.linalg as la

In [14]:
@pyimport numpy.linalg as la

In [15]:
@pyimport matplotlib.pyplot as plt

## So here we can use the python package qutip in python.

The home page is <a href="http://qutip.org">Qutip home page</a>. Various tutorials can be found <a href="http://qutip.org/tutorials.html">here</a>.


In [16]:
@pyimport qutip as qt

In [17]:
qt.qeye(2)

PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  1.]]

In [18]:
x=qt.phasegate(pi/2)*qt.phasegate(pi/2)*qt.phasegate(pi/2)

PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 1.+0.j  0.+0.j]
 [ 0.+0.j  0.-1.j]]

### note the format we have a q object, in python its x.dims, in julia x[:dims]

In [19]:
x[:dims]

2×1 Array{Int64,2}:
 2
 2

In [20]:
qt.superop_reps[:_pauli_basis]

PyObject <function _pauli_basis at 0x1449ff0d0>

In [21]:
superTest=qt.superop_reps[:_super_to_superpauli](qt.to_super(qt.sigmay()))

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

In [22]:
qt.sigmax()

PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.  1.]
 [ 1.  0.]]

In [23]:
test=qt.sigmay()

PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.+0.j  0.-1.j]
 [ 0.+1.j  0.+0.j]]

In [24]:
(pycall(pybuiltin("map"),PyAny,qt.to_super, [qt.qeye(2), qt.sigmax(), qt.sigmay()]))

PyObject <map object at 0x1442b95f8>

In [25]:
qt.sigmaz()

PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [26]:
qt.superop_reps["_SINGLE_QUBIT_PAULI_BASIS"]

PyObject (Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  1.]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.  1.]
 [ 1.  0.]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.+0.j  0.-1.j]
 [ 0.+1.j  0.+0.j]], Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]])

In [27]:
## This is the Julia version of Chris Granade code in python

function to_superpauli(S):
    """
    Converts a superoperator in the column-stacking basis to the Pauli basis. Note that
    the argument is assumed to act on qubits.
    """
    sqobj=qt.to_super(S)
    nq=round.(Int64,np.log2(sqobj[:shape][1])/2)
    # Using pycall 
    B=pycall(qt.superop_reps["_pauli_basis"],PyAny,nq)
    sq=np.sqrt(2^nq)
    # or pyeval
    B=py"$B/$sq"
    sqobj = B[:dag]()[:__mul__](sqobj[:__mul__](B))
    return sqobj
end



to_superpauli (generic function with 1 method)

In [28]:
## We have all one qubits in julia in operatorCliffords
# convert to a Qobj and then use superoperator

to_superpauli(qt.Qobj(operatorCliffords[2]))

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = False
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]]

In [29]:
rs=qt.rand_super_bcsz(rank=2)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = False
Qobj data =
[[ 0.44018364+0.j         -0.09366099+0.37717307j -0.09366099-0.37717307j
   0.72627049+0.j        ]
 [-0.08613917-0.37071206j -0.26296569+0.02272718j -0.07992730-0.04802067j
   0.00218126+0.02332043j]
 [-0.08613917+0.37071206j -0.07992730+0.04802067j -0.26296569-0.02272718j
   0.00218126-0.02332043j]
 [ 0.55981636+0.j          0.09366099-0.37717307j  0.09366099+0.37717307j
   0.27372951+0.j        ]]

In [30]:
ks=qt.to_kraus(rs)

4-element Array{PyCall.PyObject,1}:
 PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.65566304 -5.10961237e-18j -0.04710744 +5.41352784e-01j]
 [-0.08611269 -6.12298372e-01j -0.41988258 -9.78594035e-03j]]                    
 PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[-0.09562018 -3.38585722e-02j  0.65649717 -1.58867042e-17j]
 [ 0.37697890 -1.88091938e-01j -0.01873685 -3.11418200e-01j]]                    
 PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[  1.90559683e-09 +1.16232050e-09j   9.49882301e-10 -1.30068574e-09j]
 [  4.60239131e-09 -2.13125266e-09j   3.17066641e-09 +7.95873379e-09j]]
 PyObject Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[  3.88787071e-10 -4.91556314e-09j  -1.93125721e-09 -1.45238856e-09j]
 [  7.15343166e-09 -6.66449679e-10j  -1.67233550e-09 +5.5063

In [31]:
qt.kraus_to_choi(ks)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[ 0.44018364+0.j         -0.08613917+0.37071206j -0.09366099-0.37717307j
  -0.26296569-0.02272718j]
 [-0.08613917-0.37071206j  0.55981636+0.j         -0.07992730-0.04802067j
   0.09366099+0.37717307j]
 [-0.09366099+0.37717307j -0.07992730+0.04802067j  0.72627049+0.j
   0.00218126-0.02332043j]
 [-0.26296569+0.02272718j  0.09366099-0.37717307j  0.00218126+0.02332043j
   0.27372951+0.j        ]]

## Of course we have all these in julia courtesy of marcuscp

In [32]:
jks=[i[:full]() for i in ks]

4-element Array{Array{Complex{Float64},2},1}:
 Complex{Float64}[0.655663-5.10961e-18im -0.0471074+0.541353im; -0.0861127-0.612298im -0.419883-0.00978594im]         
 Complex{Float64}[-0.0956202-0.0338586im 0.656497-1.58867e-17im; 0.376979-0.188092im -0.0187369-0.311418im]           
 Complex{Float64}[1.9056e-9+1.16232e-9im 9.49882e-10-1.30069e-9im; 4.60239e-9-2.13125e-9im 3.17067e-9+7.95873e-9im]   
 Complex{Float64}[3.88787e-10-4.91556e-9im -1.93126e-9-1.45239e-9im; 7.15343e-9-6.6645e-10im -1.67234e-9+5.50634e-9im]

In [33]:
round.(kraus2choi(jks),3)

4×4 Array{Complex{Float64},2}:
   0.44+0.0im    -0.086+0.371im  -0.094-0.377im  -0.263-0.023im
 -0.086-0.371im    0.56+0.0im     -0.08-0.048im   0.094+0.377im
 -0.094+0.377im   -0.08+0.048im   0.726+0.0im     0.002-0.023im
 -0.263+0.023im   0.094-0.377im   0.002+0.023im   0.274+0.0im  

In [34]:
qt.kraus_to_choi(ks)

PyObject Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[ 0.44018364+0.j         -0.08613917+0.37071206j -0.09366099-0.37717307j
  -0.26296569-0.02272718j]
 [-0.08613917-0.37071206j  0.55981636+0.j         -0.07992730-0.04802067j
   0.09366099+0.37717307j]
 [-0.09366099+0.37717307j -0.07992730+0.04802067j  0.72627049+0.j
   0.00218126-0.02332043j]
 [-0.26296569+0.02272718j  0.09366099-0.37717307j  0.00218126+0.02332043j
   0.27372951+0.j        ]]

### That should be enough to be getting on with...